name: Deploy Firebase Site
author: danielmillan
branding:
  icon: box
  color: blue
description: This action allows you to deploy a site on firebase hosting

inputs:
  firebase-token:
    description: Token generated to authenticate in firebase
    required: true
  resources-name:
    description: Name of the folder containing the resources to be deployed
    required: true
  project-name:
    description: Firebase project name
    required: true
  target-name:
    description: Target name if you need to deploy to a specific instance
    required: false

runs:
  using: "composite"
  steps:
    - name: Deploy a firebase site
      shell: bash
      run: |
        CURRENT_PATH=$(pwd)/.github/actions/pipelines-firebase-hosting
        bash $CURRENT_PATH/deploy-site.sh \
          --firebase-token=${{ inputs.firebase-token }} \
          --resources-name=${{ inputs.resources-name }} \
          --project-name=${{ inputs.project-name }}
          --target-name=${{ inputs.target-name }}